language: ruby

install:
  - gem install jekyll link-checker

script:
  - jekyll build
#  - check-links _site
  - python -mjson.tool live-deployments.geojson
  - python -mjson.tool community/psc.geojson

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.org#pycsw"
    use_notice: true
